# nelmio_api_doc: ~

nelmio_api_doc:
    documentation:
        info:
            title: Capital Service REST API
            description: Loan calculator
            version: '1.0'
    areas:
        default: 
            path_patterns:
                - ^/api(?!/doc$)
        v1:
            with_annotation: true
            name_patterns: [ v1 ]        
