controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    prefix:   '/api/v1'
    trailing_slash_on_root: false

api_login_check:
    path: /api/v1/login_check
